### PR TITLE
Documenting incompatibility with widely used linum-mode.

### PR DESCRIPTION
**Pull request by zargener**
I've spent about a hour trying to understand why left margin is not displayed and text left uncentered. Probably not just me will face this problem.

### CODE REVIEW

**Comment by rnkn** [comment]
Is there a line number mode with which it works?

**Comment by zargener** [comment]
Only line-number-mode, which displays line number in status bar.

**Comment by rnkn** [comment]
After investigation, looks like this is a bug in `linum-mode` where it's overwriting any margins settings with the minimum column width needed to display the line numbers. I've reported to bug-gnu-emacs@gnu.org and copied below:

> I set the window left margin to 25 columns, then activated linum-mode,
> which sets the left margin to 3 columns (to accommodate the number of
> figures in the total line numbers).
>
> Expected behaviour:
>
> linum-mode should only expand left margin as needed, not
> overwrite/shrink it.
>
> Example steps to reproduce:
>
> $ emacs -Q
>
> ;; in *scratch* buffer
>
> M-: (set-window-margins (selected-window) N) ;; where N is any number > 1
>
> ;; window margins are set to N columns.
>
> M-x linum-mode
>
> ;; left window margin is reduced to 1 column
>
> Suggestions to remedy:
>
> Either linum-mode.el ~ L167 should be changed to accommodate existing
> margin width, setting width to the maximum of existing or calculated
> value, or the function should test whether the calculated width exceeds
> the current margin width, and only update the window if necessary.

**Comment by zargener** [comment]
Thank you for investigation and bug report. But please describe the problem in README.md . Many people still use 24.3 and 24.4, because of their linux distros. So for 1-2 yeas this bug will be actual I think.

**Comment by rnkn** [comment]
The development version of `nlinum-mode` may be what you want: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=20674#17

**Pull request closed without merging**
