### PR TITLE
feat: Add 'fill-column as an option for olivetti-body-width

### PR DESCRIPTION
**Pull request by arikai**
I believe that emacs already provides useful variable `fill-column` that might work quite nicely with olivetti, especially considering paragraph filling (be it automatic or manual).

This PR adds 'fill-column as an option for olivetti-body-width variable and handling of such.

### CODE REVIEW

**Comment by rnkn** [comment]
It seems that great minds think alike; the other maintainer and I had already implemented this but I had neglected to push the changed. Check out the v2 branch. We need to use fill-column + 2 because otherwise the wrap character will truncate the line.

**Comment by arikai** [comment]
Ha, you're right. Might be helpful to add this to current README.md. 

v2 looks fantastic! Any estimates for the drop?

**Comment by rnkn** [comment]
The internals have been rewritten to use pixel widths instead of columns to work better with the graphical fringes, so I wanna be a bit conservative about rolling it out. It would be a big help if you could test and let me know if you hit any problems. Just email me if you find anything.

**Comment by rnkn** [comment]
Just released v2.0 which covers this feature.

**Comment by arikai** [comment]
Sorry for the late reply: just couldn't get around to test it properly.
Try out the v2 and fill report if notice anything!

**Pull request closed without merging**
