### PR TITLE
Implement border feature for olivetti-mode enabled buffers

### PR DESCRIPTION
**Pull request by KaratasFurkan**
I like to know where the window starts and ends. This PR achieves this. Also, I think it looks better.

Screenshot_20210502_172811

### CODE REVIEW

**Comment by rnkn** [comment]
Thanks again for submitting a patch. I'm a little confused about this one though; the intent is to use a different face for fringes when they're olivetti fringes?

**Comment by KaratasFurkan** [comment]
> Thanks again for submitting a patch. I'm a little confused about this one though; the intent is to use a different face for fringes when they're olivetti fringes?

Yes

**Comment by rnkn** [comment]
I see. This is quite particular to your individual setup, so how about doing it as a theme with the face remapping on the `-on-hook` and `-off-hook` and we'll put it in `contrib/`?

**Comment by KaratasFurkan** [comment]
I did not fully understand. Do you mean separating this feature to a file like `contrib/borders.el`?

**Comment by rnkn** [comment]
Yeah but as a theme, so `contrib/olivetti-theme.el`. You can put arbitrary code into a theme. Here's an example: https://github.com/rnkn/fountain-mode/blob/master/contrib/fountain-theme.el

**Comment by KaratasFurkan** [comment]
OK, I will do that today or tomorrow evening.

**Comment by rnkn** [comment]
This is implemented in the v2 branch if you'd like to test it out.

**Comment by KaratasFurkan** [comment]
It looks great, I will definitely try it soon, thanks :+1: 

Sorry for leaving this PR, I couldn't find time to spend on it. We can close this now right?

**Comment by rnkn** [comment]
No worries.

**Pull request closed without merging**
