### PR TITLE
Make visual-line-mode an option

### PR DESCRIPTION
**Pull request by larstvei**
Is this pretty much what you had in mind? (Ref #45)

### CODE REVIEW

**Comment by rnkn** [comment]
Ah I'm sorry I've lead you astray! I didn't realise but the hook is called whenever `olivetti-mode` is called. I was thinking it was like a major mode hook. Given this, using the hook is not the best way.

You original idea to just add an `olivetti-enable-visual-line-mode` boolean is best.

**Comment by larstvei** [comment]
Haha, okey! I think the last commit should work 👍

**Comment by rnkn** [comment]
I made a couple of adjustments. We still need to have visual-line-mode on as default, otherwise the majority of people are gonna think something broke (assuming the majority don't do your same manual intervention to disable it).

If this suits your needs do you wanna merge?

**Comment by larstvei** [comment]
Okey! I misunderstood you in the issue, thinking that you wanted it off be default. I agree with keeping it on. I’ll merge it!

**Comment by rnkn** [comment]
Cool. I likewise misunderstood and thought you wanted it off by default.

**Pull request merged**
