### PR TITLE
Using min-margins window parameter

### PR DESCRIPTION
**Pull request by rnkn**
@larstvei can you look this over if you get a chance?

### CODE REVIEW

**Comment by rnkn** [comment]
p.s. While it looks like a lot of code changes, it's mostly rearranging to functions before their first call.

**Comment by larstvei** [comment]
Sure thing!

**Comment by larstvei** [comment]
It looks like text scaling breaks because `olivetti-set-margins` is called with no arguments (due to it being on the `text-scale-mode-hook`. Changing it to `olivetti-set-all-margins` seems to work, but it might be better to just wrap it in a function that calls it with the current window?

**Comment by larstvei** [comment]
Here is a small patch you can try 🙂

```
From 8ded154c618e2a280e0df9a438e9ad1d4b7c64c8 Mon Sep 17 00:00:00 2001
From: Lars Tveito <larstvei@ifi.uio.no>
Date: Mon, 13 Apr 2020 18:31:24 +0200
Subject: [PATCH] Fix text-scale-mode

---
 olivetti.el | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/olivetti.el b/olivetti.el
index 9691c4f..f3d7d83 100644
--- a/olivetti.el
+++ b/olivetti.el
@@ -332,7 +332,7 @@ body width set with `olivetti-body-width'."
   (if olivetti-mode
       (progn
         (add-hook 'text-scale-mode-hook
-                  #'olivetti-set-margins t t)
+                  #'olivetti-set-all-margins t t)
         (cond ((<= emacs-major-version 24)
                (add-hook 'window-configuration-change-hook
                          #'olivetti-set-all-margins t t))
@@ -352,7 +352,7 @@ body width set with `olivetti-body-width'."
         (unless olivetti--visual-line-mode (visual-line-mode 1))
         (olivetti-set-all-margins))
     (remove-hook 'text-scale-mode-hook
-                 #'olivetti-set-margins t)
+                 #'olivetti-set-all-margins t)
     (remove-hook 'window-configuration-change-hook
                  #'olivetti-set-all-margins t)
     (remove-hook 'window-size-change-functions
-- 
2.21.0
```

**Comment by rnkn** [comment]
Thanks. That fixed the `text-scale-mode` problem. I also renamed the functions for clarity. Now `olivetti-set-window` will set a single window's margins, and `olivetti-set-buffer-windows` will set all windows of the buffer.

**Comment by rnkn** [comment]
Merging this but I won't tag it for a while.

**Pull request merged**
